// Auto-generated by load_all — do not edit
export default interface CtxNs {
  api: {
    issues: typeof import("./api/issues").default;
    issues_$id: typeof import("./api/issues_$id").default;
    issues_$id_comments: typeof import("./api/issues_$id_comments").default;
    issues_$id_delete: typeof import("./api/issues_$id_delete").default;
    issues_$id_status: typeof import("./api/issues_$id_status").default;
  };
  auth: {
    session_from_cookie: typeof import("./auth/session_from_cookie").default;
  };
  db: {
    exec: typeof import("./db/exec").default;
    migrate: typeof import("./db/migrate").default;
    query: typeof import("./db/query").default;
    start: typeof import("./db/start").default;
    stop: typeof import("./db/stop").default;
  };
  issues: {
    http: typeof import("./issues/http").default;
    http_$id: typeof import("./issues/http_$id").default;
  };
  misc: {
    counter_proc_increment: typeof import("./misc/counter_proc_increment").default;
    counter_proc_read: typeof import("./misc/counter_proc_read").default;
    greet: typeof import("./misc/greet").default;
    http_: typeof import("./misc/http_").default;
    http_health: typeof import("./misc/http_health").default;
    http_user_$id: typeof import("./misc/http_user_$id").default;
    route_add: typeof import("./misc/route_add").default;
  };
  server: {
    start: typeof import("./server/start").default;
    stop: typeof import("./server/stop").default;
  };
  system: {
    start: typeof import("./system/start").default;
    stop: typeof import("./system/stop").default;
  };
  ui: {
    escapeHtml: typeof import("./ui/escapeHtml").default;
    index: typeof import("./ui/index").default;
    issues: typeof import("./ui/issues").default;
    issues_$id: typeof import("./ui/issues_$id").default;
    issues_$id_edit: typeof import("./ui/issues_$id_edit").default;
    layout: typeof import("./ui/layout").default;
    login: typeof import("./ui/login").default;
    logout: typeof import("./ui/logout").default;
  };
  state: {
    db: import("./db/state").State;
    server: import("./server/state").State;
    [key: string]: any;
  };
}
