// Auto-generated by load_all — do not edit
export default interface CtxFns {
  api_issues: typeof import("./api_issues").default;
  api_issues_$id: typeof import("./api_issues_$id").default;
  api_issues_$id_comments: typeof import("./api_issues_$id_comments").default;
  api_issues_$id_delete: typeof import("./api_issues_$id_delete").default;
  api_issues_$id_status: typeof import("./api_issues_$id_status").default;
  counter_proc_increment: typeof import("./counter_proc_increment").default;
  counter_proc_read: typeof import("./counter_proc_read").default;
  db_exec: typeof import("./db_exec").default;
  db_migrate: typeof import("./db_migrate").default;
  db_query: typeof import("./db_query").default;
  db_start: typeof import("./db_start").default;
  db_stop: typeof import("./db_stop").default;
  escapeHtml: typeof import("./escapeHtml").default;
  greet: typeof import("./greet").default;
  http_: typeof import("./http_").default;
  http_health: typeof import("./http_health").default;
  http_issues: typeof import("./http_issues").default;
  http_issues_$id: typeof import("./http_issues_$id").default;
  http_ui: typeof import("./http_ui").default;
  http_ui_issues: typeof import("./http_ui_issues").default;
  http_ui_issues_$id: typeof import("./http_ui_issues_$id").default;
  http_ui_issues_$id_edit: typeof import("./http_ui_issues_$id_edit").default;
  http_ui_login: typeof import("./http_ui_login").default;
  http_ui_logout: typeof import("./http_ui_logout").default;
  http_user_$id: typeof import("./http_user_$id").default;
  index: typeof import("./index").default;
  layout: typeof import("./layout").default;
  route_add: typeof import("./route_add").default;
  server_start: typeof import("./server_start").default;
  server_stop: typeof import("./server_stop").default;
  session_from_cookie: typeof import("./session_from_cookie").default;
  system_start: typeof import("./system_start").default;
  system_stop: typeof import("./system_stop").default;
}
