import { resolve } from "path";
import { Glob } from "bun";
import ctx from "./ctx";

const session: any = {};
const projectDir = resolve(".");
const skip = new Set(["ctx.ts", "repl-proc-start.ts", "repl_send.ts", "ctx_fns.d.ts"]);

function extractName(path: string): string {
  const file = path.split("/").pop() || "";
  return file.replace(/\.ts$/, "");
}

function registerRoute(name: string, handler: Function) {
  if (!ctx.routes) ctx.routes = {};
  let pattern: string;
  if (name.startsWith("http_")) {
    // http_ui_issues_$id -> /ui/issues/$id
    pattern = "/" + name.slice(5).replace(/_/g, "/");
  } else if (name.startsWith("api_")) {
    // api_issues_$id -> /api/issues/$id
    pattern = "/" + name.replace(/_/g, "/");
  } else {
    pattern = "/" + name.replace(/_/g, "/");
  }
  ctx.routes[pattern] = handler;
  return pattern;
}

async function handleReload(path: string) {
  const abs = resolve(path.endsWith(".ts") ? path : path + ".ts");
  const mod = await import(`${abs}?t=${Date.now()}`);
  const name = extractName(path);
  (ctx.fns as any)[name] = mod.default;

  if (name.startsWith("http_")) {
    const pattern = registerRoute(name, mod.default);
    return { ok: true, name, route: pattern, path: abs };
  }
  if (name.startsWith("api_")) {
    const pattern = registerRoute(name, mod.default);
    return { ok: true, name, route: pattern, path: abs };
  }

  return { ok: true, name, path: abs };
}

async function handleEval(code: string) {
  const names = Object.keys(ctx.fns);
  const values = Object.values(ctx.fns);
  const fn = new Function(...names, "ctx", "session", `return (async () => (${code}))()`);
  const result = await fn(...values, ctx, session);
  return { result };
}

async function handleLoadAll() {
  const glob = new Glob("*.ts");
  const loaded: string[] = [];
  for await (const file of glob.scan(projectDir)) {
    if (file.endsWith(".test.ts") || file.endsWith(".tmp.ts") || file.endsWith(".d.ts") || skip.has(file)) continue;
    try {
      const abs = resolve(projectDir, file);
      const mod = await import(`${abs}?t=${Date.now()}`);
      if (!mod.default) continue;
      const name = file.replace(/\.ts$/, "");
      (ctx.fns as any)[name] = mod.default;
      if (name.startsWith("http_") || name.startsWith("api_")) {
        registerRoute(name, mod.default);
      }
      loaded.push(name);
    } catch {}
  }
  await genCtxFnsDts();
  return { loaded, count: loaded.length };
}

async function genCtxFnsDts() {
  const glob = new Glob("*.ts");
  const lines: string[] = [];
  for await (const file of glob.scan(projectDir)) {
    if (file.endsWith(".test.ts") || file.endsWith(".tmp.ts") || file.endsWith(".d.ts") || skip.has(file)) continue;
    const name = file.replace(/\.ts$/, "");
    lines.push(`  ${name}: typeof import("./${name}").default;`);
  }
  lines.sort();
  const content = `// Auto-generated by load_all — do not edit\nexport default interface CtxFns {\n${lines.join("\n")}\n}\n`;
  await Bun.write(resolve(projectDir, "ctx_fns.d.ts"), content);
}

const server = Bun.serve({
  port: 3001,
  async fetch(req) {
    if (req.method !== "POST") {
      return new Response("POST /repl", { status: 405 });
    }

    try {
      const body: any = await req.json();

      if (body.op === "load_all") {
        const res = await handleLoadAll();
        return Response.json(res);
      }

      if (body.op === "reload") {
        const res = await handleReload(body.path);
        return Response.json(res);
      }

      if (body.op === "eval") {
        const res = await handleEval(body.code);
        return Response.json(res);
      }

      return Response.json({ error: "unknown op" }, { status: 400 });
    } catch (e: any) {
      return Response.json({ error: e.message, stack: e.stack }, { status: 500 });
    }
  },
});

console.log(`repl server on http://localhost:${server.port}`);
