// Auto-generated by load_all — do not edit
import _api_issues from "./api/issues";
import _api_issues_$id from "./api/issues_$id";
import _api_issues_$id_comments from "./api/issues_$id_comments";
import _api_issues_$id_delete from "./api/issues_$id_delete";
import _api_issues_$id_status from "./api/issues_$id_status";
import _auth_session_from_cookie from "./auth/session_from_cookie";
import _db_exec from "./db/exec";
import _db_migrate from "./db/migrate";
import _db_query from "./db/query";
import _db_start from "./db/start";
import _db_stop from "./db/stop";
import _issues_http from "./issues/http";
import _issues_http_$id from "./issues/http_$id";
import _misc_counter_proc_increment from "./misc/counter_proc_increment";
import _misc_counter_proc_read from "./misc/counter_proc_read";
import _misc_greet from "./misc/greet";
import _misc_http_ from "./misc/http_";
import _misc_http_health from "./misc/http_health";
import _misc_http_user_$id from "./misc/http_user_$id";
import _misc_route_add from "./misc/route_add";
import _server_start from "./server/start";
import _server_stop from "./server/stop";
import _system_start from "./system/start";
import _system_stop from "./system/stop";
import _ui_escapeHtml from "./ui/escapeHtml";
import _ui_index from "./ui/index";
import _ui_issues from "./ui/issues";
import _ui_issues_$id from "./ui/issues_$id";
import _ui_issues_$id_edit from "./ui/issues_$id_edit";
import _ui_layout from "./ui/layout";
import _ui_login from "./ui/login";
import _ui_logout from "./ui/logout";

export default function test_ctx() {
  const ctx = {
    state: {},
    routes: {},
    api: {
      issues: _api_issues,
      issues_$id: _api_issues_$id,
      issues_$id_comments: _api_issues_$id_comments,
      issues_$id_delete: _api_issues_$id_delete,
      issues_$id_status: _api_issues_$id_status,
    },
    auth: {
      session_from_cookie: _auth_session_from_cookie,
    },
    db: {
      exec: _db_exec,
      migrate: _db_migrate,
      query: _db_query,
      start: _db_start,
      stop: _db_stop,
    },
    issues: {
      http: _issues_http,
      http_$id: _issues_http_$id,
    },
    misc: {
      counter_proc_increment: _misc_counter_proc_increment,
      counter_proc_read: _misc_counter_proc_read,
      greet: _misc_greet,
      http_: _misc_http_,
      http_health: _misc_http_health,
      http_user_$id: _misc_http_user_$id,
      route_add: _misc_route_add,
    },
    server: {
      start: _server_start,
      stop: _server_stop,
    },
    system: {
      start: _system_start,
      stop: _system_stop,
    },
    ui: {
      escapeHtml: _ui_escapeHtml,
      index: _ui_index,
      issues: _ui_issues,
      issues_$id: _ui_issues_$id,
      issues_$id_edit: _ui_issues_$id_edit,
      layout: _ui_layout,
      login: _ui_login,
      logout: _ui_logout,
    },
  } as any;
  _system_start(ctx, { env: "test" });
  return ctx;
}
